Marketing/src/main/java/org/gomaneh/marketing/model/Category.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gomaneh.marketing.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author davood
 */
@Entity
@Table(name = "CATEGORY")
@XmlRootElement
@Cacheable(false)
@NamedQueries({
    @NamedQuery(name = "Category.findAll", query = "SELECT c FROM Category c")
    , @NamedQuery(name = "Category.findById", query = "SELECT c FROM Category c WHERE c.id = :id")
    , @NamedQuery(name = "Category.findByName", query = "SELECT c FROM Category c WHERE c.name = :name")
    , @NamedQuery(name = "Category.findByStatus", query = "SELECT c FROM Category c WHERE c.status = :status")
    , @NamedQuery(name = "Category.findByUpdateat", query = "SELECT c FROM Category c WHERE c.updateat = :updateat")})
public class Category implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID")
    private Integer id;
    @Size(max = 128)
    @Column(name = "NAME")
    private String name;
    @Column(name = "STATUS")
    private Integer status=0;
    @Column(name = "UPDATEAT")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateat;
    @OneToMany(mappedBy = "parrent",orphanRemoval = true,fetch = FetchType.EAGER)
    private Collection<Category> categoryCollection;
    @JoinColumn(name = "PARRENT", referencedColumnName = "ID")
    @ManyToOne
    private Category parrent;
    @JoinColumn(name = "EMPLOYEE", referencedColumnName = "ID")
    @ManyToOne
    private Employee employee;
    @OneToMany(mappedBy = "category")
    private Collection<Product> productCollection;
    @Column(name="PRIORITY")
    private int priority=1;
    @Column(name="COLOR")
    private String color="ffffff";
    @Column(name="IMAGE")
    private String image;
    public Category() {
    }

    public Category(Integer id) {
        this.id = id;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public Integer getId() {
        return id;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getUpdateat() {
        return updateat;
    }

    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    @XmlTransient
    public Collection<Category> getCategoryCollection() {
        return categoryCollection;
    }

    public void setCategoryCollection(Collection<Category> categoryCollection) {
        this.categoryCollection = categoryCollection;
    }

    public Category getParrent() {
        return parrent;
    }

    public void setParrent(Category parrent) {
        this.parrent = parrent;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @XmlTransient
    public Collection<Product> getProductCollection() {
        return productCollection;
    }

    public void setProductCollection(Collection<Product> productCollection) {
        this.productCollection = productCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Category)) {
            return false;
        }
        Category other = (Category) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return name;
    }
    
}

Marketing/src/main/java/org/gomaneh/marketing/controller/CategoryController.java
package org.gomaneh.marketing.controller;

import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import org.gomaneh.marketing.model.Category;
import org.gomaneh.marketing.controller.util.JsfUtil;
import org.gomaneh.marketing.controller.util.JsfUtil.PersistAction;
import org.gomaneh.marketing.bean.CategoryFacade;

import java.io.Serializable;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;
import javax.imageio.ImageIO;
import javax.servlet.http.Part;
import org.omnifaces.cdi.ViewScoped;
import org.primefaces.event.TreeDragDropEvent;
import org.primefaces.model.CroppedImage;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

@Named("categoryController")
@ViewScoped
public class CategoryController implements Serializable {

    @EJB
    private org.gomaneh.marketing.bean.CategoryFacade ejbFacade;
    private List<Category> items = null;
    private Category selected;
    private TreeNode root;
    private TreeNode selectedNode;
    private Part part;
    private CroppedImage cropper;
    private File temp;

    public CategoryController() {
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
        if (selectedNode != null) {
            selected = (Category) selectedNode.getData();
        }
    }

    public Category getSelected() {
        return selected;
    }

    public void setSelected(Category selected) {
        this.selected = selected;
    }

    public void createTree(TreeNode node, Category ctg) {
        for (Category c : ctg.getCategoryCollection()) {
            TreeNode n = new DefaultTreeNode(c, node);
            n.setExpanded(true);
            createTree(n, c);
        }
    }

    public Part getPart() {
        return part;
    }

    public void setPart(Part part) {
        this.part = part;
    }

    public CroppedImage getCropper() {
        return cropper;
    }

    public void setCropper(CroppedImage cropper) {
        this.cropper = cropper;
    }

    public File getTemp() {
        return temp;
    }

    public void setTemp(File temp) {
        this.temp = temp;
    }

    public TreeNode getRoot() {
        root = new DefaultTreeNode(null, null);
        for (Category c : ejbFacade.parents()) {
            TreeNode n = new DefaultTreeNode(c, root);
            n.setExpanded(true);
            createTree(n, c);
        }
        return root;
    }

    public void onDragDrop(TreeDragDropEvent event) {
        TreeNode dragNode = event.getDragNode();

        TreeNode parent = dragNode.getParent();
        Category src = (Category) dragNode.getData();
        src.setParrent((Category) parent.getData());
        int i = 0;
        for (TreeNode n : parent.getChildren()) {
            if (i == Integer.valueOf(dragNode.getRowKey()) || !dragNode.getData().equals(n.getData())) {
                ((Category) n.getData()).setPriority(i);
                ejbFacade.edit((Category) n.getData());
            }
            i++;
        }
    }

    public void setRoot(TreeNode root) {
        this.root = root;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CategoryFacade getFacade() {
        return ejbFacade;
    }

    public Category prepareCreate() {
        selected = new Category();
        initializeEmbeddableKey();
        return selected;
    }

    public void uploadImage() throws IOException {
        if (part != null) {
            ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
            String home = context.getRealPath("/resources/");
            File dir = new File(home + "/temp");
            if (!dir.exists()) {
                dir.mkdirs();
            }
            String name = System.currentTimeMillis() + ".png";
            temp = new File(dir.getAbsolutePath() + "/" + name);
            Files.copy(part.getInputStream(), temp.toPath(), new CopyOption[]{StandardCopyOption.REPLACE_EXISTING});
        }
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CategoryCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() throws IOException {
        if (cropper != null) {
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(cropper.getBytes()));
            BufferedImage tmp = new BufferedImage(300, 150, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = (Graphics2D) tmp.getGraphics();
            g.drawImage(img, 0, 0, 300, 150, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);
            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            String home = System.getProperty("user.home");
            File dir = new File(home + "/images/thumb");
            if (!dir.exists()) {
                dir.mkdirs();
            }
            File out = new File(home + "/images/" + selected.getName() + ".png");
            File outThumb = new File(home + "/images/thumb/" + selected.getName() + ".png");
            if (out.exists()) {
                out.delete();
            }
            if (outThumb.exists()) {
                outThumb.delete();
            }
            ImageIO.write(tmp, "png", outThumb);
            ImageIO.write(img, "png", out);
            if (temp.exists()) {
                temp.delete();
            }
            selected.setImage(selected.getName() + ".png");
        }
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CategoryUpdated"));
    }

    public void destroy() {
        String home = System.getProperty("user.home");
        File dir = new File(home + "/images/thumb");
        if (!dir.exists()) {
            dir.mkdirs();
        }
        File out = new File(home + "/images/" + selected.getName() + ".png");
        File outThumb = new File(home + "/images/thumb/" + selected.getName() + ".png");
        if (out.exists()) {
            out.delete();
        }
        if (outThumb.exists()) {
            outThumb.delete();
        }
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CategoryDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Category> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<Category> getChildList() {
        return getFacade().mainCategories();
    }

    public Category getCategory(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Category> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Category> getItemsAvailableSelectOne() {

        return getFacade().findAll();
    }

    public List<SelectItem> getSelectitemsCategories() {
        List<SelectItem> itemList = new ArrayList<>();
        itemList.add(new SelectItem(null,""));
        getFacade().findAll().forEach((ctg) -> {
            itemList.add(new SelectItem(ctg, ctg.getName()));
        });
        return itemList;
    }

    @FacesConverter(forClass = Category.class)
    public static class CategoryControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CategoryController controller = (CategoryController) facesContext.getApplication().getELResolver().

Marketing/src/main/webapp/inventory/category/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o='http://omnifaces.org/ui'
      xmlns:bnu="http://bootsfaces.net/ui">

    <ui:composition>

        <bnu:modal closable="true" closeOnEscape="true" styleClass="createModal" >
            <h:form id="CategoryCreateForm" enctype="multipart/form-data">
                <h:panelGroup id="display" rendered="#{categoryController.selected != null}">
                    <bnu:row>
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="عنوان" for="name" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <p:inputText styleClass="form-control" id="name" value="#{categoryController.selected.name}" title="عنوان" required="true" requiredMessage="عنوان دسته بندی را وارد کنید" />
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column>  
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="دسته بندی والد" for="parrent" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <h:selectOneMenu styleClass="form-control" style="width:100%" id="parrent" value="#{categoryController.selected.parrent}" >
                                        <f:selectItem itemLabel="دسته بندی اصلی" itemValue="" />
                                        <f:selectItems value="#{categoryController.itemsAvailableSelectOne}"
                                                       var="parrentItem"
                                                       itemValue="#{parrentItem}"/>
                                    </h:selectOneMenu>
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column>  
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="رنگ زمینه" for="color" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <p:colorPicker  id='color' value="#{categoryController.selected.color}" required="true" requiredMessage="لطفا رنگ زمینه دسته بندی را انتخاب کنید." />
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column> 

                    </bnu:row>
                    <p:commandLink styleClass="btn btn-info" actionListener="#{categoryController.create}" value="#{bundle.Save}"  update="display,:CategoryListForm,:growl" oncomplete="handleSubmitModal(args,'createModal');" />
                    <p:commandLink styleClass="btn btn-danger" type="button" value="#{bundle.Cancel}" onclick="$('.createModal').modal('hide')"/>
                </h:panelGroup>
            </h:form>
        </bnu:modal>
    </ui:composition>
</html>

Marketing/src/main/webapp/inventory/category/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:bnu="http://bootsfaces.net/ui">

    <ui:composition>

        <bnu:modal closable="true" closeOnEscape="true" styleClass="editModal" >
            <h:form id="CategoryEditForm">
                <h:panelGroup id="display" rendered="#{categoryController.selected != null}">
                     <bnu:row>
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="عنوان" for="name" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <p:inputText styleClass="form-control" id="name" value="#{categoryController.selected.name}" title="عنوان" required="true" requiredMessage="عنوان دسته بندی را وارد کنید" />
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column>  
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="دسته بندی والد" for="parrent" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <h:selectOneMenu styleClass="form-control" style="width:100%" id="parrent" value="#{categoryController.selected.parrent}" >
                                        <f:selectItem itemLabel="دسته بندی اصلی" itemValue="" />
                                        <f:selectItems value="#{categoryController.itemsAvailableSelectOne}"
                                                       var="parrentItem"
                                                       itemValue="#{parrentItem}"/>
                                    </h:selectOneMenu>
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column>  
                        <bnu:column col-lg="12" col-md="12" col-sm="12" col-xs="12">
                            <bnu:row>
                                <bnu:column col-lg="3" col-md="3" col-sm="4" col-xs="12">
                                    <p:outputLabel value="رنگ زمینه" for="color" />
                                </bnu:column>
                                <bnu:column col-lg="9" col-md="9" col-sm="8" col-xs="12">
                                    <p:colorPicker  id='color' value="#{categoryController.selected.color}" required="true" requiredMessage="لطفا رنگ زمینه دسته بندی را انتخاب کنید." />
                                </bnu:column>
                            </bnu:row> 
                        </bnu:column> 

                        </bnu:row>
                    <p:commandLink styleClass="btn btn-info" actionListener="#{categoryController.update}" value="#{bundle.Save}" update="display,:CategoryListForm,:growl" oncomplete="handleSubmitModal(args,'editModal');"/>
                    <p:commandLink styleClass="btn btn-danger" type="button" value="#{bundle.Cancel}" onclick="$('editModal').modal('hide')"/>
                </h:panelGroup>
            </h:form>
        </bnu:modal>

    </ui:composition>
</html>

Marketing/src/main/webapp/inventory/category/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o='http://omnifaces.org/ui'
      xmlns:bnu="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition>
        <h:form id="CategoryListForm">
            <p:dataTable value="#{categoryController.items}" var="item">
                <f:facet name="header">
                    <bnu:row>
                        <bnu:column colLg="6" colMd="6" colSm="6" colXs="6">
                            <h4 class="title">
                                دسته بندی ها
                            </h4>
                        </bnu:column>
                        <bnu:column style="text-align: left" colLg="6" colMd="6" colSm="6" colXs="6">
                            <p:commandLink styleClass="btn btn-primary" actionListener="#{categoryController.prepareCreate()}" update=":CategoryCreateForm" oncomplete="$('.createModal').modal()">
                                <span class="fa fa-plus"></span> #{bundle.Create}
                            </p:commandLink>
                            <p:commandLink styleClass="btn btn-info" actionListener="#{productController.setPage('product/List')}" update=":empanel">
                                <span class="fa fa-product-hunt"></span> محصولات
                            </p:commandLink>
                        </bnu:column>
                    </bnu:row>
                </f:facet>
                <p:column width="50">
                    <f:facet name="header">
                        <h:outputText value="ردیف"/>
                    </f:facet>
                    <h:outputText value="#{item.id}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="نام دسته بندی"/>
                    </f:facet>
                    <h:outputText value="#{item.name}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="دسته بندی والد"/>
                    </f:facet>
                    <h:outputText value="#{item.parrent.name}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="#"/>
                    </f:facet>
                    <p:commandLink styleClass="btn btn-success" action="#{categoryController.setSelected(item)}"  update=":CategoryEditForm" oncomplete="$('.editModal').modal()" >
                        <span class="fa fa-edit"></span>
                        #{bundle.Edit}
                    </p:commandLink>
                    <p:commandLink style="margin-right: 5px" styleClass="btn btn-danger" action="#{categoryController.setSelected(item)}" update="@form" actionListener="#{categoryController.destroy}" >
                        <span class="fa fa-remove"></span>
                        #{bundle.Delete}
                        <p:confirm />
                    </p:commandLink>
                </p:column>
            </p:dataTable>
        </h:form>
        <ui:include src="Create.xhtml"/>
        <ui:include src="Edit.xhtml"/>
    </ui:composition>

</html>

Marketing/src/main/webapp/inventory/category/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CategoryViewDlg" widgetVar="CategoryViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewCategoryTitle}">
            <h:form id="CategoryViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{categoryController.selected != null}">
                        <h:outputText value="#{bundle.ViewCategoryLabel_id}"/>
                        <h:outputText value="#{categoryController.selected.id}" title="#{bundle.ViewCategoryTitle_id}"/>
                        <h:outputText value="#{bundle.ViewCategoryLabel_name}"/>
                        <h:outputText value="#{categoryController.selected.name}" title="#{bundle.ViewCategoryTitle_name}"/>
                        <h:outputText value="#{bundle.ViewCategoryLabel_status}"/>
                        <h:outputText value="#{categoryController.selected.status}" title="#{bundle.ViewCategoryTitle_status}"/>
                        <h:outputText value="#{bundle.ViewCategoryLabel_updateat}"/>
                        <h:outputText value="#{categoryController.selected.updateat}" title="#{bundle.ViewCategoryTitle_updateat}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewCategoryLabel_parrent}"/>
                        <h:outputText value="#{categoryController.selected.parrent}" title="#{bundle.ViewCategoryTitle_parrent}"/>
                        <h:outputText value="#{bundle.ViewCategoryLabel_employee}"/>
                        <h:outputText value="#{categoryController.selected.employee}" title="#{bundle.ViewCategoryTitle_employee}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="CategoryViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>